webapp/Models/AccountViewModels.cs
#region Using

using System.ComponentModel.DataAnnotations;

#endregion

namespace SmartAdminMvc.Models
{
    public class AccountLoginModel
    {
        [Required]
        public string Email { get; set; }

        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        public string ReturnUrl { get; set; }
        public bool RememberMe { get; set; }
    }

    public class AccountForgotPasswordModel
    {
        [Required]
        [EmailAddress]
        public string Email { get; set; }
    }

    public class AccountResetPasswordModel
    {
        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [Compare("Password")]
        public string PasswordConfirm { get; set; }
    }

    public class AccountRegistrationModel
    {
        public string Username { get; set; }

        [Required]
        [EmailAddress]
        public string Email { get; set; }

        [Required]
        [EmailAddress]
        [Compare("Email")]
        public string EmailConfirm { get; set; }

        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [Compare("Password")]
        public string PasswordConfirm { get; set; }
    }
}

webapp/Models/Configuraciones/DepartamentosViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SmartAdminMvc.Models.Configuraciones
{
    public class DepartamentosViewModel
    {
        public int idDepartamentos { get; set; }
        public string descripcion { get; set; }
    }
}

webapp/Areas/Landing/Controllers/LandingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SmartAdminMvc.Areas.Landing.Controllers
{
    public class LandingController : Controller
    {
        //
        // GET: /Landing/Index
        public ActionResult Index()
        {
            return View();
        }
	}
}

webapp/Controllers/AccountController.cs
#region Using

using System;
using System.Data.Entity.Validation;
using System.Linq;
using System.Security.Principal;
using System.Threading.Tasks;
using System.Web.Mvc;
using System.Web.Security;
using Microsoft.Ajax.Utilities;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using SmartAdminMvc.Models;

#endregion

namespace SmartAdminMvc.Controllers
{
    [Authorize]
    public class AccountController : Controller
    {
        
        // GET: /account/login
        [AllowAnonymous]
        public ActionResult Login(string returnUrl)
        {
            // Store the originating URL so we can attach it to a form field
            var viewModel = new AccountLoginModel { ReturnUrl = returnUrl };

            return View(viewModel);
        }

        // POST: /account/login
        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Login(AccountLoginModel viewModel)
        {
            
            if (!ModelState.IsValid)
                return View(viewModel);
            
           if(Membership.ValidateUser(viewModel.Email, viewModel.Password))
            {

                FormsAuthentication.SetAuthCookie(viewModel.Email, viewModel.RememberMe);
                if (!string.IsNullOrEmpty(viewModel.ReturnUrl)) return Redirect(viewModel.ReturnUrl);
                return RedirectToAction("Index", "Home");
            }

            return View(viewModel);
        }

        // GET: /account/error
        [AllowAnonymous]
        public ActionResult Error()
        {

            return View();
        }


        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Login", "Account");
        }

               

        // GET: /account/lock
        [AllowAnonymous]
        public ActionResult Lock()
        {
            return View();
        }
    }
}

webapp/Controllers/ConfiguracionesController.cs
using SmartAdminMvc.DB;
using SmartAdminMvc.Models.Configuraciones;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SmartAdminMvc.Controllers
{
    public class ConfiguracionesController : Controller
    {

        #region Departamentos

        // GET: Configuraciones
        public ActionResult Departamentos()
        {
            return View();
        }

        public JsonResult GetDepartamentos()
        {
            using (var db = new ConsultorioEntities())
            {
                var model = db.Departamentos.Select(x => new DepartamentosViewModel
                {
                    idDepartamentos = x.idDepartamento,
                    descripcion = x.descripcion
                }).ToList();

                return Json(new { data = model }, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpGet]
        public ActionResult CrearDepartamentos()
        {
            return PartialView(new DepartamentosViewModel());
        }


        [HttpPost]
        public ActionResult CrearDepartamentos(DepartamentosViewModel model)
        {
            try
            {
                using (var db = new ConsultorioEntities())
                {
                    var departamento = new Departamentos
                    {
                        descripcion = model.descripcion
                    };

                    db.Departamentos.Add(departamento);

                    db.SaveChanges();

                    return Json(new { ok = true }, JsonRequestBehavior.AllowGet);

                }
            }
            catch (Exception ex)
            {
                return Json(new { ok = false }, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpGet]
        public ActionResult EditarDepartamentos(int idDepartamento)
        {
            using (var db = new ConsultorioEntities())
            {
                var model = db.Departamentos.Where(x => x.idDepartamento == idDepartamento).
                    Select(x => new DepartamentosViewModel
                    {
                        idDepartamentos = x.idDepartamento,
                        descripcion = x.descripcion
                    }).FirstOrDefault();

                return PartialView(model);
            }
        }

        [HttpPost]
        public ActionResult EditarDepartamentos(DepartamentosViewModel model)
        {
            try
            {
                using (var db = new ConsultorioEntities())
                {
                    var departamento = db.Departamentos.FirstOrDefault(x => x.idDepartamento == model.idDepartamentos);

                    departamento.descripcion = model.descripcion;

                    db.SaveChanges();

                    return Json(new { ok = true }, JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception ex)
            {
                return Json(new { ok = false }, JsonRequestBehavior.AllowGet);
            }
        }

        #endregion

    }
}

webapp/Controllers/HomeController.cs
#region Using

using System.Web.Mvc;

#endregion

namespace SmartAdminMvc.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        // GET: home/index
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Social()
        {
            return View();
        }

        // GET: home/inbox
        public ActionResult Inbox()
        {
            return View();
        }

        // GET: home/widgets
        public ActionResult Widgets()
        {
            return View();
        }

        // GET: home/chat
        public ActionResult Chat()
        {
            return View();
        }
    }
}

webapp/Views/Configuraciones/CrearDepartamentos.cshtml
@model SmartAdminMvc.Models.Configuraciones.DepartamentosViewModel


<div class="jarviswidget jarviswidget-color-blueDark jarviswidget-sortable" id="wid-id-0" data-widget-colorbutton="false" data-widget-editbutton="false" data-widget-custombutton="false" role="widget" style="">
    <header role="heading">
        <h2><i class="fa fa- fa-newspaper-o"></i> Crear Departamento </h2>
    </header>


    <div role="content">
        <div class="widget-body">

            <form id="frmDepartamento" method="post">

                <div class="form-horizontal">

                    <div class="form-group">
                        <label class="col-lg-12">Nombre</label>
                        @*<label class="col-lg-12">Nombre: </label>*@
                        <div class="col-lg-12">
                            @Html.EditorFor(model => model.descripcion, new { htmlAttributes = new { @class = "form-control" } })
                            
                        </div>
                    </div>

                    <div class="widget-footer">
                        <button type='button' class='btn btn-danger' data-dismiss='modal'> Cerrar</button>
                        <button type="submit" class="btn btn-success"> Crear</button>
                    </div>

                </div>
            </form>

        </div>


    </div>

</div>

<style>

    .invalid {
        color: #a94442;
        /*margin-left: 12px;*/
    }
</style>


<script>

    $(document).ready(function () {

        $('#frmDepartamento').validate({
            ignore: [],
            rules: {
                descripcion: {
                    required: true
                }
            },
            messages: {
                descripcion: {
                    required: "Nombre del departamento requerido"
                }
            },
            submitHandler: function (form) {
                $.ajax({
                    url: "@Url.Action("CrearDepartamentos","Configuraciones")",
                    type: "post",
                    dataType: "JSON",
                    data: $(form).serialize(),
                    success: function (data) {
                        if (data.ok == true) {
                            exito("Advertencia","Departamento creado Exitosamente!");
                            $("#myModal").modal("hide");
                            dtDepartamentos.ajax.reload(null, false);
                        }
                        else {
                            fallo("Advertencia", "Error al tratar crear el Departamento!");
                        }
                    }
                });
            }
        })

    })

</script>

webapp/Views/Configuraciones/Departamentos.cshtml
<div class="row">
    <article class="col-sm-12 col-md-12 col-lg-3 sortable-grid ui-sortable" id="CreatePartial" style="display:none;"></article>

    <article class="col-sm-12 col-md-12 col-lg-12 sortable-grid ui-sortable">

        <!-- Widget ID (each widget will need unique ID)-->
        <div class="jarviswidget jarviswidget-color-blueDark jarviswidget-sortable" id="wid-id-3" data-widget-colorbutton="false" data-widget-editbutton="false" data-widget-custombutton="false" role="widget" style="">
            <header role="heading">
                <h2><i class="fa fa- fa-newspaper-o"></i> Listado de Departamentos </h2>
                <div class="widget-toolbar" role="menu">
                    <a class="btn btn-warning js-create-departamentos">  Crear Departamento</a>
                </div>
            </header>

            <!-- widget div-->
            <div role="content">
                <!-- widget content -->
                <div class="widget-body no-padding">

                    <table class="table table-responsive table-bordered table-striped" id="dtDepartamentos" width="100%">
                        <thead>
                            <tr>
                                <th>id</th>
                                <th>Nombre</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody></tbody>
                    </table>

                </div>


            </div>

        </div>

    </article>

</div>

<div class="modal bounceInDown animated" id="myModal" role="dialog">
    <div class="modal-dialog modal-lg">
        <div class="modal-body" id="modalBody">
            <div class="form-group">

            </div>
        </div>
    </div>
</div>

@section pagespecific {

    <script>

        var dtDepartamentos;

        $(document).ready(function () {

            dtDepartamentos = $('#dtDepartamentos').DataTable({
                "sDom": "<'dt-toolbar'<'col-xs-12 col-sm-6 hidden-xs'f><'col-sm-6 col-xs-12 hidden-xs'<'toolbar'>>r>" +
                    "t" +
                    "<'dt-toolbar-footer'<'col-sm-6 col-xs-12 hidden-xs'i><'col-xs-12 col-sm-6'p>>",
                "autoWidth": true,
                "DisplayStart": 1,
                "processing": true,
                "stateSave": true,
                "ajax": {
                    url: '@Url.Action("GetDepartamentos", "Configuraciones")',
                    "type": "GET",
                    "datatype": "json",
                    "async": false,
                    "error": function (xhr, status, error) { }
                },
                "columns": [

                    { "data": "idDepartamentos", "autoWidth": true },
                    { "data": "descripcion", "autoWidth": true },
                    {
                        "data": null,
                        "render": function (data, type, row) {

                            return '<div class="btn-group">' +
                                '<button type="button" class="btn btn-link dropdown-toggle btn-xs" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">' +
                                'Acciones  <span class="caret"></span>' +
                                '</button>' +
                                '<ul class="dropdown-menu">' +
                                '<li><a href="#"class="js-editar" data-iddepartamento=' + row.idDepartamentos+'>Editar</a></li>' +
                                '</ul>' +
                                '</div>';
                        }
                    }
                ],
                "language": {
                    "paginate": {
                        "previous": "Anterior",
                        "next": "Siguiente"
                    },
                    "info": "Pagina _PAGE_ de _PAGES_ de _TOTAL_ Registros"
                },
                "pageLength": 35
            });

        });


        $(document).on('click', '.js-create-departamentos', function () {
            $.ajax({
            url: '@Url.Action("CrearDepartamentos", "Configuraciones")',
            type: "get",
            success: function (data) {

                $("#modalBody").html(data);
                $('#myModal').modal({ backdrop: 'static', keyboard: false })
                $("#myModal").modal("show");
                
                }
            });
        });

        $(document).on('click', '.js-editar', function () {

            var iddepartamento = $(this).data('iddepartamento');

            $.ajax({
            url: '@Url.Action("EditarDepartamentos", "Configuraciones")',
                type: "get",
                data: { idDepartamento: iddepartamento },
                success: function (data) {
                    $("#modalBody").html(data);
                    $('#myModal').modal({ backdrop: 'static', keyboard: false })
                    $("#myModal").modal("show");
                }
            });

            

        });


    </script>

}

webapp/Views/Configuraciones/EditarDepartamentos.cshtml
@model SmartAdminMvc.Models.Configuraciones.DepartamentosViewModel


<div class="jarviswidget jarviswidget-color-blueDark jarviswidget-sortable" id="wid-id-0" data-widget-colorbutton="false" data-widget-editbutton="false" data-widget-custombutton="false" role="widget" style="">
    <header role="heading">
        <h2><i class="fa fa- fa-newspaper-o"></i> Crear Departamento </h2>
    </header>


    <div role="content">
        <div class="widget-body">

            <form id="frmDepartamento" method="post">

                <div class="form-horizontal">

                    <div class="form-group" hidden>
                        <label class="col-lg-12">Id</label>
                        @*<label class="col-lg-12">Nombre: </label>*@
                        <div class="col-lg-12">
                            @Html.EditorFor(model => model.idDepartamentos, new { htmlAttributes = new { @class = "form-control" } })

                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-lg-12">Nombre</label>
                        @*<label class="col-lg-12">Nombre: </label>*@
                        <div class="col-lg-12">
                            @Html.EditorFor(model => model.descripcion, new { htmlAttributes = new { @class = "form-control" } })

                        </div>
                    </div>

                    <div class="widget-footer">
                        <button type='button' class='btn btn-danger' data-dismiss='modal'> Cerrar</button>
                        <button type="submit" class="btn btn-success"> Crear</button>
                    </div>

                </div>
            </form>

        </div>


    </div>

</div>

<style>

    .invalid {
        color: #a94442;
        /*margin-left: 12px;*/
    }
</style>

<script>

    $(document).ready(function () {

        $('#frmDepartamento').validate({
            ignore: [],
            rules: {
                descripcion: {
                    required: true
                }
            },
            messages: {
                descripcion: {
                    required: "Nombre del departamento requerido"
                }
            },
            submitHandler: function (form) {
                $.ajax({
                    url: "@Url.Action("EditarDepartamentos", "Configuraciones")",
                    type: "post",
                    dataType: "JSON",
                    data: $(form).serialize(),
                    success: function (data) {
                        if (data.ok == true) {
                            exito("Advertencia","Departamento editado Exitosamente!");
                            $("#myModal").modal("hide");
                            dtDepartamentos.ajax.reload(null, false);
                        }
                        else {
                            fallo("Advertencia", "Error al tratar editar el Departamento!");
                        }
                    }
                });
            }
        })

    })

</script>

webapp/Views/Home/Index.cshtml
<!-- MAIN CONTENT -->
<div id="content">
    
    <section id="widget-grid" class="">



    </section>


</div>

webapp/Views/Shared/_Aside.cshtml
  
<aside id="left-panel">


    <nav>
        
        <ul>
            <li>
                <a href="#" title="Dashboard"><i class="fa fa-lg fa-fw fa-home"></i> <span class="menu-item-parent">Dashboard</span></a>
                <ul>
                    <li>
                        <a href="@Url.Action("index", "home")" title="Dashboard"><span class="menu-item-parent">Analytics Dashboard</span></a>
                    </li>
                </ul>
            </li>

        </ul>
    </nav>
    <span class="minifyme" data-action="minifyMenu">
        <i class="fa fa-arrow-circle-left hit"></i>
    </span>

</aside>

webapp/Views/Shared/_CurrentUser.cshtml
<div class="login-info">
    <span>
        <a href="javascript:void(0);" id="show-shortcut" data-action="toggleShortcut">
            <img src="~/content/img/avatars/sunny.png" alt="me" class="online" />
            <span>@User.Identity.Name.ToLower()</span>
            <i class="fa fa-angle-down"></i>
        </a>
    </span>
</div>

webapp/Views/Shared/_Footer.cshtml
    <!-- PAGE FOOTER -->
<div class="page-footer">
    <div class="row">
        <div class="col-xs-12 col-sm-6">
            <span class="txt-color-white">SmartAdmin 1.8.1 <span class="hidden-xs"> - Web Application Framework</span> © 2011-2016</span>
        </div>

        <div class="col-xs-6 col-sm-6 text-right hidden-xs">
            <div class="txt-color-white inline-block">
                <i class="txt-color-blueLight hidden-mobile">Last account activity <i class="fa fa-clock-o"></i> <strong>52 mins ago &nbsp;</strong> </i>
                <div class="btn-group dropup">
                    <button class="btn btn-xs dropdown-toggle bg-color-blue txt-color-white" data-toggle="dropdown">
                        <i class="fa fa-link"></i> <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu pull-right text-left">
                        <li>
                            <div class="padding-5">
                                <p class="txt-color-darken font-sm no-margin">Download Progress</p>
                                <div class="progress progress-micro no-margin">
                                    <div class="progress-bar progress-bar-success" style="width: 50%;"></div>
                                </div>
                            </div>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <div class="padding-5">
                                <p class="txt-color-darken font-sm no-margin">Server Load</p>
                                <div class="progress progress-micro no-margin">
                                    <div class="progress-bar progress-bar-success" style="width: 20%;"></div>
                                </div>
                            </div>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <div class="padding-5">
                                <p class="txt-color-darken font-sm no-margin">Memory Load <span class="text-danger">*critical*</span></p>
                                <div class="progress progress-micro no-margin">
                                    <div class="progress-bar progress-bar-danger" style="width: 70%;"></div>
                                </div>
                            </div>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <div class="padding-5">
                                <button class="btn btn-block btn-default">refresh</button>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- END PAGE FOOTER -->

webapp/Views/Shared/_Header.cshtml
    <!-- HEADER -->
<header id="header">
    <div id="logo-group">

        <!-- PLACE YOUR LOGO HERE -->
        <span id="logo"> <img src="~/content/img/logo.png" alt="SmartAdmin"> </span>
        
    </div>
    
    <section id="top-right">
        @if (@Model is HelperResult)
        {
            @Model
        }
        else
        {
            <div class="pull-right">
                @Html.Partial("_TopRight")
            </div>
        }
    </section>
</header>
<!-- END HEADER -->

webapp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en-us" id="@ViewBag.PageId" class="smart-style-3">
<head>
    <meta charset=" utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <title> SmartAdmin - MVC5 </title>
    <meta name="description" content="">
    <meta name="author" content="">

    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">

    <!-- Basic Styles -->
    @Styles.Render("~/content/smartadmin")
    <!-- FAVICONS -->
    <link rel="shortcut icon" href="~/content/img/favicon/favicon.ico" type="image/x-icon">
    <link rel="icon" href="~/content/img/favicon/favicon.ico" type="image/x-icon">

    <!-- GOOGLE FONT -->
    <link rel="stylesheet" href="//fonts.googleapis.com/css?family=Open+Sans:400italic,700italic,300,400,700">

    <!-- Specifying a Webpage Icon for Web Clip
         Ref: https://developer.apple.com/library/ios/documentation/AppleApplications/Reference/SafariWebContent/ConfiguringWebApplications/ConfiguringWebApplications.html -->
    <link rel="apple-touch-icon" href="~/content/img/splash/sptouch-icon-iphone.png">
    <link rel="apple-touch-icon" sizes="76x76" href="~/content/img/splash/touch-icon-ipad.png">
    <link rel="apple-touch-icon" sizes="120x120" href="~/content/img/splash/touch-icon-iphone-retina.png">
    <link rel="apple-touch-icon" sizes="152x152" href="~/content/img/splash/touch-icon-ipad-retina.png">

    <!-- iOS web-app metas : hides Safari UI Components and Changes Status Bar Appearance -->
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">

    <!-- Startup image for web apps -->
    <link rel="apple-touch-startup-image" href="~/content/img/splash/ipad-landscape.png" media="screen and (min-device-width: 481px) and (max-device-width: 1024px) and (orientation:landscape)">
    <link rel="apple-touch-startup-image" href="~/content/img/splash/ipad-portrait.png" media="screen and (min-device-width: 481px) and (max-device-width: 1024px) and (orientation:portrait)">
    <link rel="apple-touch-startup-image" href="~/content/img/splash/iphone.png" media="screen and (max-device-width: 320px)">
</head>
<body class="@ViewBag.PageClass smart-style-3">
    @{ Html.RenderPartial("_Header", RenderSection("topright", false)); }
    @{ Html.RenderPartialIf("_Aside", User.Identity.IsAuthenticated); }
    <div id="main" role="main">
        @{ Html.RenderPartialIf("_Ribbon", User.Identity.IsAuthenticated); }
        
        <div id="content">
            @RenderBody()
        </div>

    </div>
    @if (Request.IsAuthenticated)
    {
        Html.RenderPartial("_Footer");
        Html.RenderPartialIf("_Tiles", Settings.EnableTiles);
    }
    @{ Html.RenderPartial("_Scripts", RenderSection("pagespecific", false)); }

</body>

</html>



<script>

    function exito(titulo, messages) {

        $.smallBox({
            title: titulo,
            content: "<i ></i> <i> " + messages+ " </i>",
            color: "#659265",
            iconSmall: "fa fa-check fa-2x fadeInRight animated",
            timeout: 9000
        });
    }

    function fallo(titulo,mesage) {

        $.smallBox({
            title: titulo,
            content: "<i ></i> <i>" + mesage + "</i>",
            color: "#C20202",
            iconSmall: "fa fa-times fadeInRight animated",
            timeout: 9000
        });
    }


</script>

webapp/Views/Shared/_Ribbon.cshtml
<div id="ribbon">

 
    <ol class="breadcrumb">
        <li>Home</li>
        <li>Dashboard</li>
    </ol>
    

</div>

webapp/Views/Shared/_Scripts.cshtml
<!-- Link to Google CDN's jQuery + jQueryUI; fall back to local -->
<script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<script> if (!window.jQuery) { document.write('<script src="/scripts/libs/jquery-2.1.1.min.js"><\/script>'); } </script>
<script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script>
<script> if (!window.jQuery.ui) { document.write('<script src="/scripts/libs/jquery-ui-1.10.3.min.js"><\/script>'); } </script>

<!-- IMPORTANT: SmartAdmin Core -->
@Scripts.Render("~/scripts/smartadmin")

@if (Request.IsAuthenticated)
{
    <!-- PACE LOADER - turn this on if you want ajax loading to show (caution: uses lots of memory on iDevices)-->
    <script data-pace-options='{ "restartOnRequestAfter": true }' src="~/scripts/plugin/pace/pace.min.js"></script>
    <!-- Demo purpose only! -->
    <script src="/scripts/demo.min.js"></script>
}

<!-- Voice command : plugin -->
<script src="~/scripts/speech/voicecommand.min.js"></script>

<!-- SmartChat UI : plugin -->
@Scripts.Render("~/scripts/smart-chat")

<!-- DataTables : plugin -->
@Scripts.Render("~/scripts/datatables")

<!-- jQGrid : plugin -->
@Scripts.Render("~/scripts/jq-grid")

<!-- Forms : plugin -->
@Scripts.Render("~/scripts/forms")

<!-- Flot Chart Plugin: Flot Engine, Flot Resizer, Flot Tooltip, Morris, Sparkline, EasyPie -->
@Scripts.Render("~/scripts/charts")

<!-- Vector Maps Plugin: Vectormap engine, Vectormap language -->
@Scripts.Render("~/scripts/vector-map")

<!-- Full Calendar -->
@Scripts.Render("~/scripts/full-calendar")

<!-- DO NOT REMOVE : GLOBAL FUNCTIONS! -->
<script>
    $(document).ready(function () {
        pageSetUp();
        drawBreadCrumb();
    });
</script>

@if (@Model is HelperResult)
{
    @Model
}
<!-- Your GOOGLE ANALYTICS CODE Below-->
    @*<script type="text/javascript">
    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'xx-xxxxxxxx-x']);
    _gaq.push(['_trackPageview']);

    (function () {
        var ga = document.createElement('script');
        ga.type = 'text/javascript';
        ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0];
        s.parentNode.insertBefore(ga, s);
    })();
</script>*@

webapp/Views/Shared/_Tiles.cshtml
<!-- SHORTCUT AREA : With large tiles (activated via clicking user name tag)
Note: These tiles are completely responsive,
you can add as many as you like
-->
<div id="shortcut">
    <ul>
        <li>
            <a href="@Url.Action("inbox", "home")" class="jarvismetro-tile big-cubes bg-color-blue"> <span class="iconbox"> <i class="fa fa-envelope fa-4x"></i> <span>Mail <span class="label pull-right bg-color-darken">14</span></span> </span> </a>
        </li>
        <li>
            <a href="@Url.Action("calendar", "home")" class="jarvismetro-tile big-cubes bg-color-orangeDark"> <span class="iconbox"> <i class="fa fa-calendar fa-4x"></i> <span>Calendar</span> </span> </a>
        </li>
        <li>
            <a href="@Url.Action("googlemap", "home")" class="jarvismetro-tile big-cubes bg-color-purple"> <span class="iconbox"> <i class="fa fa-map-marker fa-4x"></i> <span>Maps</span> </span> </a>
        </li>
        <li>
            <a href="@Url.Action("invoice", "misc")" class="jarvismetro-tile big-cubes bg-color-blueDark"> <span class="iconbox"> <i class="fa fa-book fa-4x"></i> <span>Invoice <span class="label pull-right bg-color-darken">99</span></span> </span> </a>
        </li>
        <li>
            <a href="@Url.Action("gallery", "appviews")" class="jarvismetro-tile big-cubes bg-color-greenLight"> <span class="iconbox"> <i class="fa fa-picture-o fa-4x"></i> <span>Gallery </span> </span> </a>
        </li>
        <li>
            <a href="@Url.Action("profile", "appviews")" class="jarvismetro-tile big-cubes selected bg-color-pinkDark"> <span class="iconbox"> <i class="fa fa-user fa-4x"></i> <span>My Profile </span> </span> </a>
        </li>
    </ul>
</div>
<!-- END SHORTCUT AREA -->